let
    StartDate = #date(2016, 1, 1),
    EndDate = DateTime.Date(DateTime.LocalNow()),
    Length = Duration.Days(EndDate - StartDate),
    Source = List.Dates(StartDate, Length, #duration(1, 0, 0, 0)),

    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),

    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Year", "Month Name", each Date.MonthName([Date]), type text),
    #"Inserted Day Name" = Table.AddColumn(#"Inserted Month Name", "Day Name", each Date.DayOfWeekName([Date]), type text),
    #"Inserted Month" = Table.AddColumn(#"Inserted Day Name", "Month", each Date.Month([Date]), Int64.Type),
    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Month", "Day of Week", each Date.DayOfWeek([Date]) +1, Int64.Type),
    #"Inserted First Characters" = Table.AddColumn(#"Inserted Day of Week", "MMM", each Text.Start([Month Name], 3), type text),
    #"Inserted First Characters1" = Table.AddColumn(#"Inserted First Characters", "DDD", each Text.Start([Day Name], 3), type text),
    #"Added Custom" = Table.AddColumn(#"Inserted First Characters1", "MMM-YY", each [MMM] & "-" &Text.From([Year]-2000)),
    Calendar = Table.ReorderColumns(#"Added Custom",{"Date", "Year", "Month", "Day of Week", "Day Name", "MMM", "Month Name", "DDD", "MMM-YY"})
in
    Calendar
    
    
